# Generated by Django 4.1.4 on 2022-12-08 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("todos", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="todo",
            table="todos",
        ),
    ]
